language: node_js
node_js:
  - "8"
  - "lts/*"

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "8"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        on:
          tags: true
