language: node_js
node_js:
  - "8"
  - "lts/*"

jobs:
  include:
    - node_js: "6"
      if: tag IS blank
      script: npm run build
      before_install:
        - npm install -g npm@latest
    - stage: npm release
      if: tag IS present
      node_js: "6"
      script: npm run build
      before_install:
        - npm install -g npm@latest
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
